### ISSUE TITLE
how does this compare to tabout.nvim?

### ISSUE THREAD

**Issue by daUnknownCoder** [ysmb-wtsg/in-and-out.nvim#2]
https://github.com/abecodes/tabout.nvim

does this do the same thing?

**Comment by ysmb-wtsg** [comment]
@daUnknownCoder 
That is exactly the same…
I ended up creating this plugin without knowing about that plugin.
 Thank you for letting me know!

**Comment by daUnknownCoder** [comment]
> Thank you for letting me know!

happened with me quite a few times, i can feel you 😢
